version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:11
    container_name: fursona-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fursona_db
      MYSQL_USER: fursonauser
      MYSQL_PASSWORD: fursonapass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - fursona-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fursona-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=fursonauser
      - DB_PASSWORD=fursonapass
      - DB_NAME=fursona_db
    env_file:
      - ./backend/.env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - fursona-network
    volumes:
      - ./backend/uploads:/app/uploads

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fursona-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - fursona-network

networks:
  fursona-network:
    driver: bridge

volumes:
  mariadb_data:
